# coding=utf-8

# imports


# -------   function utils section    -------
# load json file
import json


def process_inout_fl(path):
    """
    :return:
    """
    with open(path, 'r') as fl:
        pass


# use json save fl
def save_fl(fl: list, path: str) -> str:
    """
    This function use json module save fl to disk.
    :param fl: fl array generated by quantization function
    :param path: path for fl to save.
    :return:
    """
    with open(path, 'w') as file:
        json.dump(fl, file)
    return path
